[pytest]
minversion = 6.0
addopts = --cov=pyXLMS --cov-report=html --cov-fail-under=80
pythonpath = .
testpaths =
    tests
filterwarnings =
    error
    ignore::pyparsing.warnings.PyparsingDeprecationWarning
