name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
type: "Bug"
assignees:
  - michabirklbauer
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: version-pyxlms
    attributes:
      label: pyXLMS Version
      description: What version of pyXLMS are you running?
      placeholder: pyXLMS 1.0.0
    validations:
      required: true
  - type: textarea
    id: version-python
    attributes:
      label: Python Version
      description: What version of Python are you running?
      placeholder: Python 3.12.9
    validations:
      required: true
  - type: textarea
    id: version-os
    attributes:
      label: Operating System
      description: What operating system (and architecture) are you running pyXLMS on?
      placeholder: Windows 11 Pro (x86_x64)
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: Thanks for getting in touch with us - in case you want us to reply via email please leave your contact info.
      placeholder: ex. email@example.com
    validations:
      required: false
