name: Question
description: Question about pyXLMS or related topics.
title: "[Question]: "
labels: ["question","triage"]
type: "Task"
projects: ["hgb-bin-proteomics/5"]
assignees:
  - michabirklbauer
body:
  - type: markdown
    attributes:
      value: |
        Please preferably ask your questions in [Discussions](https://github.com/hgb-bin-proteomics/pyXLMS/discussions)!

        But we are happy to help in any case! :)
  - type: textarea
    id: question
    attributes:
      label: Question:
      description: Please give us as many details as possible.
      placeholder: How...?
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: Thanks for getting in touch with us - in case you want us to reply via email please leave your contact info.
      placeholder: ex. email@example.com
    validations:
      required: false
