[server]
maxUploadSize = 200

[theme]
base = "light"
primaryColor = "#6D4BFF"
backgroundColor = "#FAFAFA"
linkColor = "#6D4BFF"
showSidebarBorder = true

[theme.sidebar]
primaryColor = "#FAFAFA"
backgroundColor = "#6D4BFF"
textColor = "#FAFAFA"
linkColor = "#FAFAFA"
